name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📸 Calculate commit hash
        id: sha
        uses: pr-mpt/actions-commit-hash@v3

      - name: 🔨 Prepare Bun environment
        uses: oven-sh/setup-bun@v1

      - name: 🎉 Install project dependencies
        run: bun i
        working-directory: ./scripts

      - name: 🚀 Build project (Linux)
        run: bun build src/index.ts --compile --target=bun-linux-x64 --outfile ../out/cook-zip-linux-x64
        working-directory: ./scripts
      - name: 🚀 Build project (Windows)
        run: bun build src/index.ts --compile --target=bun-windows-x64 --outfile ../out/cook-zip-windows-x64.exe
        working-directory: ./scripts
      - name: 🚀 Build project (macOS)
        run: bun build src/index.ts --compile --target=bun-macos-x64 --outfile ../out/cook-zip-macos-x64
        working-directory: ./scripts

      - name: 🔒 Calculate SHA-256 hashes
        id: sha256
        run: |
          LINUX_SHA=$(sha256sum out/cook-zip-linux-x64 | awk '{ print $1 }')
          WINDOWS_SHA=$(sha256sum out/cook-zip-windows-x64.exe | awk '{ print $1 }')
          MACOS_SHA=$(sha256sum out/cook-zip-macos-x64 | awk '{ print $1 }')

          echo "LINUX_SHA=$LINUX_SHA" >> $GITHUB_ENV
          echo "WINDOWS_SHA=$WINDOWS_SHA" >> $GITHUB_ENV
          echo "MACOS_SHA=$MACOS_SHA" >> $GITHUB_ENV

          echo "::set-output name=linux_sha::$LINUX_SHA"
          echo "::set-output name=windows_sha::$WINDOWS_SHA"
          echo "::set-output name=macos_sha::$MACOS_SHA"

      - name: 📦 Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/cook-zip-linux-x64
            out/cook-zip-windows-x64.exe
            out/cook-zip-macos-x64
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body: |
            ### SHA-256 Checksums
            - Linux: `${{ steps.sha256.outputs.linux_sha }}`
            - Windows: `${{ steps.sha256.outputs.windows_sha }}`
            - macOS: `${{ steps.sha256.outputs.macos_sha }}`
